# Generated by Django 4.0.4 on 2022-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sRollNum', models.TextField()),
                ('sName', models.TextField(max_length=40)),
            ],
        ),
    ]
