# Generated by Django 4.0.4 on 2022-05-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sRollNum', models.TextField()),
                ('sName', models.TextField(max_length=40)),
                ('sDept', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
