# Generated by Django 4.0.4 on 2022-05-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students1_delete_students'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students1',
            table='myFirstDb',
        ),
    ]
