# Generated by Django 4.0.4 on 2022-11-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students1_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students1',
            table='myfirstdb',
        ),
    ]
