# Generated by Django 4.0.4 on 2023-05-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students1_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students1',
            old_name='sName',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='students1',
            old_name='sDept',
            new_name='Student_TotalMarks',
        ),
        migrations.RenameField(
            model_name='students1',
            old_name='sRollNum',
            new_name='Student_id',
        ),
    ]
